//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace StockSpider
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StockContext1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StockContext1 object using the connection string found in the 'StockContext1' section of the application configuration file.
        /// </summary>
        public StockContext1() : base("name=StockContext1", "StockContext1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockContext1 object.
        /// </summary>
        public StockContext1(string connectionString) : base(connectionString, "StockContext1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockContext1 object.
        /// </summary>
        public StockContext1(EntityConnection connection) : base(connection, "StockContext1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DayData> DayData
        {
            get
            {
                if ((_DayData == null))
                {
                    _DayData = base.CreateObjectSet<DayData>("DayData");
                }
                return _DayData;
            }
        }
        private ObjectSet<DayData> _DayData;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DayDetail> DayDetail
        {
            get
            {
                if ((_DayDetail == null))
                {
                    _DayDetail = base.CreateObjectSet<DayDetail>("DayDetail");
                }
                return _DayDetail;
            }
        }
        private ObjectSet<DayDetail> _DayDetail;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StockItem> StockItem
        {
            get
            {
                if ((_StockItem == null))
                {
                    _StockItem = base.CreateObjectSet<StockItem>("StockItem");
                }
                return _StockItem;
            }
        }
        private ObjectSet<StockItem> _StockItem;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CWZY> T_cwzy
        {
            get
            {
                if ((_T_cwzy == null))
                {
                    _T_cwzy = base.CreateObjectSet<CWZY>("T_cwzy");
                }
                return _T_cwzy;
            }
        }
        private ObjectSet<CWZY> _T_cwzy;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DayData EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDayData(DayData dayData)
        {
            base.AddObject("DayData", dayData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DayDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDayDetail(DayDetail dayDetail)
        {
            base.AddObject("DayDetail", dayDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StockItem EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStockItem(StockItem stockItem)
        {
            base.AddObject("StockItem", stockItem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_cwzy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_cwzy(CWZY cWZY)
        {
            base.AddObject("T_cwzy", cWZY);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="CWZY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CWZY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CWZY object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="stockCode">Initial value of the stockCode property.</param>
        public static CWZY CreateCWZY(global::System.Guid id, global::System.String stockCode)
        {
            CWZY cWZY = new CWZY();
            cWZY.Id = id;
            cWZY.stockCode = stockCode;
            return cWZY;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> mgjzc
        {
            get
            {
                return _mgjzc;
            }
            set
            {
                OnmgjzcChanging(value);
                ReportPropertyChanging("mgjzc");
                _mgjzc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mgjzc");
                OnmgjzcChanged();
            }
        }
        private Nullable<global::System.Decimal> _mgjzc;
        partial void OnmgjzcChanging(Nullable<global::System.Decimal> value);
        partial void OnmgjzcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> mgsy
        {
            get
            {
                return _mgsy;
            }
            set
            {
                OnmgsyChanging(value);
                ReportPropertyChanging("mgsy");
                _mgsy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mgsy");
                OnmgsyChanged();
            }
        }
        private Nullable<global::System.Decimal> _mgsy;
        partial void OnmgsyChanging(Nullable<global::System.Decimal> value);
        partial void OnmgsyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> mgxjhl
        {
            get
            {
                return _mgxjhl;
            }
            set
            {
                OnmgxjhlChanging(value);
                ReportPropertyChanging("mgxjhl");
                _mgxjhl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mgxjhl");
                OnmgxjhlChanged();
            }
        }
        private Nullable<global::System.Decimal> _mgxjhl;
        partial void OnmgxjhlChanging(Nullable<global::System.Decimal> value);
        partial void OnmgxjhlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> mgzbgjj
        {
            get
            {
                return _mgzbgjj;
            }
            set
            {
                OnmgzbgjjChanging(value);
                ReportPropertyChanging("mgzbgjj");
                _mgzbgjj = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mgzbgjj");
                OnmgzbgjjChanged();
            }
        }
        private Nullable<global::System.Decimal> _mgzbgjj;
        partial void OnmgzbgjjChanging(Nullable<global::System.Decimal> value);
        partial void OnmgzbgjjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> mgzchj
        {
            get
            {
                return _mgzchj;
            }
            set
            {
                OnmgzchjChanging(value);
                ReportPropertyChanging("mgzchj");
                _mgzchj = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mgzchj");
                OnmgzchjChanged();
            }
        }
        private Nullable<global::System.Decimal> _mgzchj;
        partial void OnmgzchjChanging(Nullable<global::System.Decimal> value);
        partial void OnmgzchjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ldzchj
        {
            get
            {
                return _ldzchj;
            }
            set
            {
                OnldzchjChanging(value);
                ReportPropertyChanging("ldzchj");
                _ldzchj = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ldzchj");
                OnldzchjChanged();
            }
        }
        private Nullable<global::System.Decimal> _ldzchj;
        partial void OnldzchjChanging(Nullable<global::System.Decimal> value);
        partial void OnldzchjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> zchj
        {
            get
            {
                return _zchj;
            }
            set
            {
                OnzchjChanging(value);
                ReportPropertyChanging("zchj");
                _zchj = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zchj");
                OnzchjChanged();
            }
        }
        private Nullable<global::System.Decimal> _zchj;
        partial void OnzchjChanging(Nullable<global::System.Decimal> value);
        partial void OnzchjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> cqfzhj
        {
            get
            {
                return _cqfzhj;
            }
            set
            {
                OncqfzhjChanging(value);
                ReportPropertyChanging("cqfzhj");
                _cqfzhj = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cqfzhj");
                OncqfzhjChanged();
            }
        }
        private Nullable<global::System.Decimal> _cqfzhj;
        partial void OncqfzhjChanging(Nullable<global::System.Decimal> value);
        partial void OncqfzhjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> zyywsr
        {
            get
            {
                return _zyywsr;
            }
            set
            {
                OnzyywsrChanging(value);
                ReportPropertyChanging("zyywsr");
                _zyywsr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zyywsr");
                OnzyywsrChanged();
            }
        }
        private Nullable<global::System.Decimal> _zyywsr;
        partial void OnzyywsrChanging(Nullable<global::System.Decimal> value);
        partial void OnzyywsrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> cwfy
        {
            get
            {
                return _cwfy;
            }
            set
            {
                OncwfyChanging(value);
                ReportPropertyChanging("cwfy");
                _cwfy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cwfy");
                OncwfyChanged();
            }
        }
        private Nullable<global::System.Decimal> _cwfy;
        partial void OncwfyChanging(Nullable<global::System.Decimal> value);
        partial void OncwfyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> jlr
        {
            get
            {
                return _jlr;
            }
            set
            {
                OnjlrChanging(value);
                ReportPropertyChanging("jlr");
                _jlr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jlr");
                OnjlrChanged();
            }
        }
        private Nullable<global::System.Decimal> _jlr;
        partial void OnjlrChanging(Nullable<global::System.Decimal> value);
        partial void OnjlrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> jzrq
        {
            get
            {
                return _jzrq;
            }
            set
            {
                OnjzrqChanging(value);
                ReportPropertyChanging("jzrq");
                _jzrq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jzrq");
                OnjzrqChanged();
            }
        }
        private Nullable<global::System.DateTime> _jzrq;
        partial void OnjzrqChanging(Nullable<global::System.DateTime> value);
        partial void OnjzrqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String stockCode
        {
            get
            {
                return _stockCode;
            }
            set
            {
                OnstockCodeChanging(value);
                ReportPropertyChanging("stockCode");
                _stockCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("stockCode");
                OnstockCodeChanged();
            }
        }
        private global::System.String _stockCode;
        partial void OnstockCodeChanging(global::System.String value);
        partial void OnstockCodeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="DayData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DayData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DayData object.
        /// </summary>
        /// <param name="stockCode">Initial value of the StockCode property.</param>
        /// <param name="area">Initial value of the Area property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="open">Initial value of the Open property.</param>
        /// <param name="high">Initial value of the High property.</param>
        /// <param name="low">Initial value of the Low property.</param>
        /// <param name="close">Initial value of the Close property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        /// <param name="adjClose">Initial value of the AdjClose property.</param>
        public static DayData CreateDayData(global::System.String stockCode, global::System.String area, global::System.DateTime date, global::System.Decimal open, global::System.Decimal high, global::System.Decimal low, global::System.Decimal close, global::System.Decimal volume, global::System.Decimal adjClose)
        {
            DayData dayData = new DayData();
            dayData.StockCode = stockCode;
            dayData.Area = area;
            dayData.Date = date;
            dayData.Open = open;
            dayData.High = high;
            dayData.Low = low;
            dayData.Close = close;
            dayData.Volume = volume;
            dayData.AdjClose = adjClose;
            return dayData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StockCode
        {
            get
            {
                return _StockCode;
            }
            set
            {
                if (_StockCode != value)
                {
                    OnStockCodeChanging(value);
                    ReportPropertyChanging("StockCode");
                    _StockCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StockCode");
                    OnStockCodeChanged();
                }
            }
        }
        private global::System.String _StockCode;
        partial void OnStockCodeChanging(global::System.String value);
        partial void OnStockCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Area
        {
            get
            {
                return _Area;
            }
            set
            {
                if (_Area != value)
                {
                    OnAreaChanging(value);
                    ReportPropertyChanging("Area");
                    _Area = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Area");
                    OnAreaChanged();
                }
            }
        }
        private global::System.String _Area;
        partial void OnAreaChanging(global::System.String value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Open
        {
            get
            {
                return _Open;
            }
            set
            {
                OnOpenChanging(value);
                ReportPropertyChanging("Open");
                _Open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Open");
                OnOpenChanged();
            }
        }
        private global::System.Decimal _Open;
        partial void OnOpenChanging(global::System.Decimal value);
        partial void OnOpenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal High
        {
            get
            {
                return _High;
            }
            set
            {
                OnHighChanging(value);
                ReportPropertyChanging("High");
                _High = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("High");
                OnHighChanged();
            }
        }
        private global::System.Decimal _High;
        partial void OnHighChanging(global::System.Decimal value);
        partial void OnHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Low
        {
            get
            {
                return _Low;
            }
            set
            {
                OnLowChanging(value);
                ReportPropertyChanging("Low");
                _Low = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Low");
                OnLowChanged();
            }
        }
        private global::System.Decimal _Low;
        partial void OnLowChanging(global::System.Decimal value);
        partial void OnLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Close
        {
            get
            {
                return _Close;
            }
            set
            {
                OnCloseChanging(value);
                ReportPropertyChanging("Close");
                _Close = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Close");
                OnCloseChanged();
            }
        }
        private global::System.Decimal _Close;
        partial void OnCloseChanging(global::System.Decimal value);
        partial void OnCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.Decimal _Volume;
        partial void OnVolumeChanging(global::System.Decimal value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AdjClose
        {
            get
            {
                return _AdjClose;
            }
            set
            {
                OnAdjCloseChanging(value);
                ReportPropertyChanging("AdjClose");
                _AdjClose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdjClose");
                OnAdjCloseChanged();
            }
        }
        private global::System.Decimal _AdjClose;
        partial void OnAdjCloseChanging(global::System.Decimal value);
        partial void OnAdjCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateAt
        {
            get
            {
                return _CreateAt;
            }
            set
            {
                OnCreateAtChanging(value);
                ReportPropertyChanging("CreateAt");
                _CreateAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateAt");
                OnCreateAtChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateAt;
        partial void OnCreateAtChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateAtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="DayDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DayDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DayDetail object.
        /// </summary>
        /// <param name="stockCode">Initial value of the StockCode property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="open">Initial value of the Open property.</param>
        /// <param name="high">Initial value of the High property.</param>
        /// <param name="low">Initial value of the Low property.</param>
        /// <param name="close">Initial value of the Close property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        /// <param name="scale">Initial value of the Scale property.</param>
        public static DayDetail CreateDayDetail(global::System.String stockCode, global::System.DateTime date, global::System.Decimal open, global::System.Decimal high, global::System.Decimal low, global::System.Decimal close, global::System.Decimal volume, global::System.Byte scale)
        {
            DayDetail dayDetail = new DayDetail();
            dayDetail.StockCode = stockCode;
            dayDetail.Date = date;
            dayDetail.Open = open;
            dayDetail.High = high;
            dayDetail.Low = low;
            dayDetail.Close = close;
            dayDetail.Volume = volume;
            dayDetail.Scale = scale;
            return dayDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StockCode
        {
            get
            {
                return _StockCode;
            }
            set
            {
                if (_StockCode != value)
                {
                    OnStockCodeChanging(value);
                    ReportPropertyChanging("StockCode");
                    _StockCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StockCode");
                    OnStockCodeChanged();
                }
            }
        }
        private global::System.String _StockCode;
        partial void OnStockCodeChanging(global::System.String value);
        partial void OnStockCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Area
        {
            get
            {
                return _Area;
            }
            set
            {
                OnAreaChanging(value);
                ReportPropertyChanging("Area");
                _Area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Area");
                OnAreaChanged();
            }
        }
        private global::System.String _Area;
        partial void OnAreaChanging(global::System.String value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Open
        {
            get
            {
                return _Open;
            }
            set
            {
                OnOpenChanging(value);
                ReportPropertyChanging("Open");
                _Open = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Open");
                OnOpenChanged();
            }
        }
        private global::System.Decimal _Open;
        partial void OnOpenChanging(global::System.Decimal value);
        partial void OnOpenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal High
        {
            get
            {
                return _High;
            }
            set
            {
                OnHighChanging(value);
                ReportPropertyChanging("High");
                _High = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("High");
                OnHighChanged();
            }
        }
        private global::System.Decimal _High;
        partial void OnHighChanging(global::System.Decimal value);
        partial void OnHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Low
        {
            get
            {
                return _Low;
            }
            set
            {
                OnLowChanging(value);
                ReportPropertyChanging("Low");
                _Low = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Low");
                OnLowChanged();
            }
        }
        private global::System.Decimal _Low;
        partial void OnLowChanging(global::System.Decimal value);
        partial void OnLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Close
        {
            get
            {
                return _Close;
            }
            set
            {
                OnCloseChanging(value);
                ReportPropertyChanging("Close");
                _Close = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Close");
                OnCloseChanged();
            }
        }
        private global::System.Decimal _Close;
        partial void OnCloseChanging(global::System.Decimal value);
        partial void OnCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.Decimal _Volume;
        partial void OnVolumeChanging(global::System.Decimal value);
        partial void OnVolumeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Scale
        {
            get
            {
                return _Scale;
            }
            set
            {
                OnScaleChanging(value);
                ReportPropertyChanging("Scale");
                _Scale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Scale");
                OnScaleChanged();
            }
        }
        private global::System.Byte _Scale;
        partial void OnScaleChanging(global::System.Byte value);
        partial void OnScaleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="stockModel", Name="StockItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StockItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StockItem object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="area">Initial value of the Area property.</param>
        public static StockItem CreateStockItem(global::System.String name, global::System.String code, global::System.String area)
        {
            StockItem stockItem = new StockItem();
            stockItem.Name = name;
            stockItem.Code = code;
            stockItem.Area = area;
            return stockItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Area
        {
            get
            {
                return _Area;
            }
            set
            {
                if (_Area != value)
                {
                    OnAreaChanging(value);
                    ReportPropertyChanging("Area");
                    _Area = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Area");
                    OnAreaChanged();
                }
            }
        }
        private global::System.String _Area;
        partial void OnAreaChanging(global::System.String value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Categories
        {
            get
            {
                return _Categories;
            }
            set
            {
                OnCategoriesChanging(value);
                ReportPropertyChanging("Categories");
                _Categories = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Categories");
                OnCategoriesChanged();
            }
        }
        private global::System.String _Categories;
        partial void OnCategoriesChanging(global::System.String value);
        partial void OnCategoriesChanged();

        #endregion
    
    }

    #endregion
    
}
